---
- hosts: docker-registries
  vars_files:
  - keys/htpasswd.base64.yml
  roles:
  - role: install-prerequisites
  - role: mount-nfs-volume
  - role: install-docker
  - role: install-docker-registry
  - role: install-image-cleaner
  - role: install-docker-registry-web

