version: '2'

services:

  gitlab:
    restart: always
    image: gitlab/gitlab-ce:10.4.3-ce.0
    ports:
    - "127.0.0.1:10080:80"
    - "0.0.0.0:10528:22"
    volumes:
    - /srv/gitlab/config:/etc/gitlab
    - /srv/gitlab/logs:/var/log/gitlab
    - /srv/gitlab/data:/var/opt/gitlab

  gitlab_runner:
    restart: always
    image: gitlab/gitlab-runner:alpine-v10.3.1
    volumes:
    - /srv/gitlab-runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
