
# Password used to join keepalived instances
keepalived_password: 4be37dc3b4c90194d1600c483e10ad1d

# Virtual addresse used as the main contact point of the controller
keepalived_virtualaddress: 10.0.2.220

# Interface to bind to keepalived
keepalived_interface: ens160

# Token used to join etcd nodes
etcd_cluster_token: 9477af68bbee1b9ae037d6fd9e7efefd

# Token used to join kubernetes workers
kubeadm_token: 1e61a2.d2b67e66edba4ca9

# Time to live for token, 0 = infinite
kubeadm_token_ttl: 0

kube_dns_ip: 10.32.0.1
