- name: Install bind
  apt:
    name: bind9
    state: latest

- name: Install dns utils
  apt:
    name: dnsutils
    state: latest

- name: Template options
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: bind

- name: Template local conf
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
    owner: bind

- name: Create directory for name db
  file:
    path: /etc/bind/infra.net
    state: directory
    owner: bind

- name: Template name db
  template:
    src: db.infra.net
    dest: /etc/bind/infra.net/db.infra.net
    owner: bind

- name: Allow writing in infra directory
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.named
    insertafter: ".*/etc/bind/.+ r,"
    line: "  /etc/bind/infra.net/** rw,"

- name: Template DDNS keys
  template:
    src: ddns.key
    dest: /etc/bind/ddns.key
    owner: bind

- name: Restart app armor
  systemd:
    name: apparmor
    state: restarted

- name: Restart bind
  systemd:
    name: bind9
    state: restarted

# TODO: find a better way
- name: Add local DNS in resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
