- set_fact: compose_local_src="{{ playbook_dir }}/dockerc-mongodb"
- set_fact: compose_remote_root="/opt"
- set_fact: compose_remote_src="{{ compose_remote_root }}/dockerc-mongodb"

- name: "Ensure mongodb data dir exists"
  file:
    path: /mongodb/data/
    state: directory
    recurse: yes

- name: "Copy docker compose directory"
  synchronize:
    src: "{{ compose_local_src }}"
    dest: "{{ compose_remote_root }}"

- debug:
    var: compose_remote_src

- docker_service:
    project_src: "{{ compose_remote_src }}"
    state: absent

- docker_service:
    project_src: "{{ compose_remote_src }}"
  register: output

- debug:
    var: output

- docker_service:
    project_src: "{{ compose_remote_src }}"
    build: no
  register: output

- debug:
    var: output

- assert:
    that: "not output.changed"

- docker_service:
    project_src: "{{ compose_remote_src }}"
    build: no
    stopped: true
  register: output

- debug:
    var: output

- assert:
    that:
      - "not mongodb.mongodb.state.running"

- docker_service:
    project_src: "{{ compose_remote_src }}"
    build: no
    restarted: true
  register: output

- debug:
    var: output

- assert:
    that:
      - "mongodb.mongodb.state.running"
