
- name: Install bind
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - bind
  - bind-utils

- name: "Start and enable bind"
  systemd:
    name: named
    state: started
    enabled: yes