- name: "Ensure apt-transport-https is installed."
  apt: name=apt-transport-https state=present


- name: "Ensure pip is installed"
  apt:
    name: python-pip
    state: present
    update_cache: yes


- name: "Ensure pip is up to date"
  pip:
    name: pip
    state: latest


- name: "Ensure docker-py is installed"
  pip:
    name: docker-py


- name: "Copy certificate in /usr/local/share/ca-certificates/"
  copy:
    src: "{{ playbook_dir }}/keys/FILLME.crt"
    dest: /usr/local/share/ca-certificates/bbuzg.crt


- name: "Update ca certificates"
  shell: update-ca-certificates
  args:
    executable: /bin/bash


