apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.7.0
networking:
  podSubnet: 10.244.0.0/16
apiServerCertSANs:
{% for host in groups['cluster'] %}
- {{ host }}
{% endfor %}
- {{ keepalived_virtualaddress }} # Virtual IP for load balancing
- {{ kube_dns_ip }} # Kube DNS IP
- 127.0.0.1
- localhost
etcd:
  endpoints:
{% for host in groups['etcd_cluster'] %}
  - http://{{ host }}:2379
{% endfor %}
