- name: "Install Apache 2"
  apt:
    name: apache2
    state: present

#- name: "Install Apache2 modules"
#  apt:
#    name: "{{ item }}"
#    state: present
#  with_items:
#      - libapache2-mod-proxy-uwsgi

- name: "Enable Apache2 modules"
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - ssl
    - headers
    - proxy_http
    - proxy_balancer
