kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-path-example-volume
  labels:
    volume-type: hostpath
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/sda1/host-path-example-volume