kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: host-path-example-claim
  namespace: volumes-examples
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume-type: hostpath