apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: volume-example-deployment
  namespace: volumes-examples
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: volume-example-deployment
    spec:
      containers:
      - name: volume-example-deployment
        image: volumes-examples:0.1
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /empty-dir
              name: empty-dir-example-volume
            - mountPath: /host-path
              name: host-path-example-volume-name
      volumes:
      - name: empty-dir-example-volume
        emptyDir: {}
      - name: host-path-example-volume-name
        persistentVolumeClaim:
          claimName: host-path-example-claim
