kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-example-volume-claim
  namespace: volumes-examples
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      volume-type: nfs