#cloud-config
network:
  version: 2
  ethernets:
    id0:
      match:
        name: ens160
      dhcp4: false
      addresses:
      - ${ip_address}/24
      gateway4: 192.168.0.1
      nameservers:
        search: []
        addresses: [192.168.0.100, 8.8.8.8]
