#cloud-config
network:
  ethernets:
    ens160:
      addresses:
      - ${ip_address}/24
      dhcp4: false
      gateway4: 192.168.0.1
      nameservers:
        addresses:
        - 192.168.0.60
        - 8.8.8.8
        search: []
  version: 2
