---
# https://raw.githubusercontent.com/kubernetes/kubernetes/v1.5.2/cluster/addons/fluentd-elasticsearch/es-controller.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: "fluentd"
  namespace: "kube-system"
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    version: "v1.22"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: "v1.22"
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      containers:
      - name: fluentd-es
        image: "gcr.io/google_containers/fluentd-elasticsearch:1.22"
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent -c /etc/kubernetes/fluentd/fluentd.conf 2>&1 >> /var/log/fluentd.log'
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu:  100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: "/etc/kubernetes/fluentd"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap: 
          name: fluentd-config

