---
- hosts: nodes
  tasks:
  - name: Update machines # Mandatory on 14/06/2018
    apt:
      upgrade: yes

  - name: Install GlusterFS components
    apt: name={{item}} state=present
    with_items:
      - glusterfs-server
      - attr

  - name: Ensure volume0 directory exists
    file:
      state: directory
      path: /data/volume0