---
- hosts: nodes
  tasks:
  - name: Update machines # Mandatory on 14/06/2018
    apt:
      upgrade: yes

  - name: Install GlusterFS components
    apt: name={{item}} state=present
    with_items:
      - glusterfs-server
      - attr

  - name: Ensure volume0 directory exists
    file:
      state: directory
      path: /data/volume0

  - name: Ensure volume0 directory exists
    file:
      state: directory
      path: /data/volume0

  - name: Peer probe for all hosts
    shell:
      cmd: "gluster peer probe {{ item }}"
      executable: /bin/bash
    with_items: "{{ groups['all'] | first }}"