---
- hosts: nodes
  tasks:
  - name: Update machines # Mandatory on 14/06/2018
    apt:
      upgrade: yes

  - name: Install GlusterFS components
    apt: name={{item}} state=present
    with_items:
      - glusterfs-server
      - attr

  - name: Ensure volume0 directory exists
    file:
      state: directory
      path: /data/volume0

  - name: Ensure volume0 directory exists
    file:
      state: directory
      path: /data/volume0

  - name: Peer probe for all hosts
    shell:
      cmd: "gluster peer probe {{ item }}"
      executable: /bin/bash
    with_items: "{{ groups['all'] | first }}"

  - name: Create gluster volume
    gluster_volume:
      state: present
      name: volume0
      bricks: /data/volume0/brick0,/data/volume0/brick0,/data/volume0/brick0
      rebalance: yes
      replicas: 3
      cluster: "{{ groups['all'] }}"
      force: yes  # Force because in vagrant volumes are on the root partition, which is not recommended
    run_once: true

  - name: start gluster volume
    gluster_volume:
      state: started
      name: volume0