
- name: "Install epel release"
  yum:
    name: epel-release
    state: present

- name: "Install prerequisites"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - byobu
  - python-pip