version: '3.4'
services:

  auto-heal:
    container_name: autoheal
    image: willfarrell/autoheal:latest
    network_mode: bridge
    environment:
    - AUTOHEAL_CONTAINER_LABEL=all
    - AUTOHEAL_INTERVAL=5m
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/localtime:/etc/localtime
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
