
- name: "Ensure ssh keys are present for root user"
  copy:
    src: "{{ item }}"
    dest: /root/.ssh
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub

- name: "Clone git repository"
  git:
    repo: "{{ deployment_repository_url }}"
    dest: "{{ deployment_repository_path }}"
    version: "{{ deployment_checkout }}"
    accept_hostkey: yes
    force: yes

