---
- hosts: jessie
  tasks:
  - include_role:
      name: install-rabbitmq
    vars:
      rabbitmq_port: "5672"
      rabbitmq_management_port: "15672"
      rabbitmq_user: "jean"
      rabbitmq_password: "claude"