bind:
  trusted_cidr: 10.0.0.0/24
  global_forwarders:
  - 8.8.8.8
  listen_addresses:
  - 10.0.0.5 # should normally be 10.20.0.5, 10.30.0.5

  zones:
  - name: mydomain.net
    reverse_name: 20.10.in-addr.arpa
    reverse_ns_address: 5.0
    serial: 201809222
    admin_mail: admin.mydomain.net
    records:
      type_a:
      - { domain: 'vm1.mydomain.net', address: '10.20.0.11', reverse_address: '11.0'}
      - { domain: 'vm2.mydomain.net', address: '10.20.0.12', reverse_address: '12.0'}
      - { domain: 'vm3.mydomain.net', address: '10.20.0.13', reverse_address: '13.0'}

  - name: mydomain.com
    reverse_name: 30.10.in-addr.arpa
    reverse_ns_address: 5.0
    serial: 201809222
    admin_mail: admin.mydomain.com
    records:
      type_a:
      - { domain: 'vm1.mydomain.com', address: '10.30.0.11', reverse_address: '11.0'}
      - { domain: 'vm2.mydomain.com', address: '10.30.0.12', reverse_address: '12.0'}
      - { domain: 'vm3.mydomain.com', address: '10.30.0.13', reverse_address: '13.0'}
