bind:
  trusted_cidr: 10.0.0.0/24
  global_forwarders:
  - 8.8.8.8

  zones:
  - name: mydomain.net
    admin_mail: admin.mydomain.net
    serial: 201809221
    reverse_name: 10.10.in-addr.arpa
    records:
    - { type: 'A', domain: 'vm1.mydomain.net', address: '10.0.10.10'}
    - { type: 'A', domain: 'vm2.mydomain.net', address: '10.0.10.11'}
    - { type: 'A', domain: 'vm3.mydomain.net', address: '10.0.10.13'}

  - name: mydomain.com
    admin_mail: admin.mydomain.com
    serial: 201809221
    reverse_name: 10.20.in-addr.arpa
    records:
    - { type: 'A', domain: 'vm1.mydomain.com', address: '10.0.20.10'}
    - { type: 'A', domain: 'vm2.mydomain.com', address: '10.0.20.11'}
    - { type: 'A', domain: 'vm3.mydomain.com', address: '10.0.20.13'}
