version: '3'
services:
  amqp:
    image: rabbitmq:3.4-management
    ports:
     - "15671:15671"
     - "15672:15672"
     - "5672:5672"
     deploy:
      restart_policy:
        condition: always
  nats:
    image: nats
    ports:
     - "6222:6222"
     - "4222:4222"
     - "8222:8222"
    deploy:
      restart_policy:
      condition: always

#docker run -d -p 6222:6222 -p 4222:4222 -p 8222:8222 nats
#docker run -d -p 15671:15671 -p 15672:15672 -p 5672:5672 rabbitmq:3.4-management