apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak-ha-postgres
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: "keycloak"
            - name: KEYCLOAK_PASSWORD
              value: "keycloak"
            - name: POSTGRES_DATABASE
              value: "keycloak"
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_PASSWORD
              value: "keycloak"
            - name: POSTGRES_PORT_5432_TCP_ADDR
              value: "10.0.4.230"
            - name: POSTGRES_PORT_5432_TCP_PORT
              value: "5432"

          readinessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 4
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /auth
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2
            successThreshold: 1

